import 'dart:io';

import 'package:firebase_storage/firebase_storage.dart';
import 'package:flutter/material.dart';
import 'package:flutter_riverpod/flutter_riverpod.dart';
import 'package:go_router/go_router.dart';
import 'package:image_picker/image_picker.dart';
import 'package:latlong2/latlong.dart';
import 'package:logements_app/core/constants/amenities.dart';
import 'package:logements_app/core/constants/app_colors.dart';
import 'package:logements_app/core/constants/togo_locations.dart';
import 'package:logements_app/data/models/listing_model.dart';
import 'package:logements_app/presentation/providers/auth_provider.dart';
import 'package:logements_app/presentation/providers/listing_provider.dart';

/// Provider pour l'étape actuelle
final currentStepProvider = StateProvider<int>((ref) => 0);

/// Provider pour les données du formulaire
final listingFormProvider = StateProvider<Map<String, dynamic>>((ref) => {});

/// Page d'ajout d'annonce avec formulaire en 6 étapes
class AddListingPage extends ConsumerStatefulWidget {
  const AddListingPage({super.key});

  @override
  ConsumerState<AddListingPage> createState() => _AddListingPageState();
}

class _AddListingPageState extends ConsumerState<AddListingPage> {
  final _formKeys = List.generate(6, (_) => GlobalKey<FormState>());
  final _pageController = PageController();

  @override
  void dispose() {
    _pageController.dispose();
    super.dispose();
  }

  void _nextStep() {
    final currentStep = ref.read(currentStepProvider);
    if (_formKeys[currentStep].currentState?.validate() ?? false) {
      _formKeys[currentStep].currentState?.save();
      if (currentStep < 5) {
        ref.read(currentStepProvider.notifier).state++;
        _pageController.nextPage(
          duration: const Duration(milliseconds: 300),
          curve: Curves.easeInOut,
        );
      } else {
        _submitListing();
      }
    }
  }

  void _previousStep() {
    final currentStep = ref.read(currentStepProvider);
    if (currentStep > 0) {
      ref.read(currentStepProvider.notifier).state--;
      _pageController.previousPage(
        duration: const Duration(milliseconds: 300),
        curve: Curves.easeInOut,
      );
    }
  }

  Future<void> _submitListing() async {
    final formData = ref.read(listingFormProvider);
    final user = ref.read(authStateProvider).value;

    if (user == null) {
      ScaffoldMessenger.of(context).showSnackBar(
        const SnackBar(content: Text('Vous devez être connecté')),
      );
      return;
    }

    // Afficher un indicateur de chargement
    showDialog(
      context: context,
      barrierDismissible: false,
      builder: (context) => const Center(child: CircularProgressIndicator()),
    );

    try {
      // Upload images to Firebase Storage
      final imageUrls = <String>[];
      if (formData['images'] != null) {
        final images = formData['images'] as List<String>;
        for (var i = 0; i < images.length; i++) {
          final imagePath = images[i];
          final storageRef = FirebaseStorage.instance
              .ref()
              .child('listings')
              .child(user.uid)
              .child('${DateTime.now().millisecondsSinceEpoch}_$i.jpg');

          await storageRef.putFile(File(imagePath));
          final url = await storageRef.getDownloadURL();
          imageUrls.add(url);
        }
      }

      // Create listing model
      final listing = ListingModel(
        id: '', // Will be generated by Firebase
        title: formData['title'] ?? '',
        description: formData['description'] ?? '',
        type: formData['type'] ?? ListingType.apartment,
        price: (formData['price'] ?? 0).toDouble(),
        city: formData['city'] ?? '',
        neighborhood: formData['neighborhood'] ?? '',
        address: formData['address'] ?? '',
        location: LatLng(
          formData['latitude'] ?? 0.0,
          formData['longitude'] ?? 0.0,
        ),
        area: (formData['area'] ?? 0).toDouble(),
        bedrooms: formData['bedrooms'] ?? 0,
        bathrooms: formData['bathrooms'] ?? 0,
        amenities: List<String>.from(formData['amenities'] ?? []),
        images: imageUrls,
        ownerId: user.uid,
        status: ListingStatus.active,
        views: 0,
        favoritesCount: 0,
        createdAt: DateTime.now(),
      );

      // Save to Firebase
      await ref.read(listingControllerProvider.notifier).createListing(listing);

      if (mounted) {
        Navigator.pop(context); // Fermer le loader
        ScaffoldMessenger.of(context).showSnackBar(
          const SnackBar(content: Text('Annonce créée avec succès!')),
        );
        context.go('/dashboard');
      }
    } catch (e) {
      if (mounted) {
        Navigator.pop(context);
        ScaffoldMessenger.of(context).showSnackBar(
          SnackBar(content: Text('Erreur: $e')),
        );
      }
    }
  }

  @override
  Widget build(BuildContext context) {
    final currentStep = ref.watch(currentStepProvider);

    return Scaffold(
      appBar: AppBar(
        title: const Text('Nouvelle annonce'),
        leading: IconButton(
          icon: const Icon(Icons.close),
          onPressed: () => _showExitConfirmation(context),
        ),
      ),
      body: Column(
        children: [
          // Indicateur de progression
          _buildStepIndicator(currentStep),

          // Contenu de l'étape
          Expanded(
            child: PageView(
              controller: _pageController,
              physics: const NeverScrollableScrollPhysics(),
              onPageChanged: (index) {
                ref.read(currentStepProvider.notifier).state = index;
              },
              children: [
                _Step1BasicInfo(formKey: _formKeys[0]),
                _Step2Location(formKey: _formKeys[1]),
                _Step3Details(formKey: _formKeys[2]),
                _Step4Amenities(formKey: _formKeys[3]),
                _Step5Images(formKey: _formKeys[4]),
                _Step6Review(formKey: _formKeys[5]),
              ],
            ),
          ),

          // Boutons de navigation
          _buildNavigationButtons(currentStep),
        ],
      ),
    );
  }

  Widget _buildStepIndicator(int currentStep) {
    final steps = [
      'Infos de base',
      'Localisation',
      'Détails',
      'Commodités',
      'Photos',
      'Révision',
    ];

    return Container(
      padding: const EdgeInsets.all(16),
      child: Row(
        children: List.generate(6, (index) {
          final isActive = index == currentStep;
          final isCompleted = index < currentStep;

          return Expanded(
            child: Column(
              children: [
                Row(
                  children: [
                    if (index > 0)
                      Expanded(
                        child: Container(
                          height: 2,
                          color: isCompleted
                              ? AppColors.primary
                              : AppColors.grey300,
                        ),
                      ),
                    Container(
                      width: 32,
                      height: 32,
                      decoration: BoxDecoration(
                        shape: BoxShape.circle,
                        color: isCompleted || isActive
                            ? AppColors.primary
                            : AppColors.grey300,
                      ),
                      child: Center(
                        child: isCompleted
                            ? const Icon(Icons.check,
                                color: AppColors.white, size: 16)
                            : Text(
                                '${index + 1}',
                                style: TextStyle(
                                  color: isActive
                                      ? AppColors.white
                                      : AppColors.grey600,
                                  fontWeight: FontWeight.bold,
                                  fontSize: 12,
                                ),
                              ),
                      ),
                    ),
                    if (index < 5)
                      Expanded(
                        child: Container(
                          height: 2,
                          color: isCompleted
                              ? AppColors.primary
                              : AppColors.grey300,
                        ),
                      ),
                  ],
                ),
                const SizedBox(height: 4),
                Text(
                  steps[index],
                  style: TextStyle(
                    fontSize: 10,
                    color: isActive ? AppColors.primary : AppColors.grey600,
                    fontWeight: isActive ? FontWeight.bold : FontWeight.normal,
                  ),
                  textAlign: TextAlign.center,
                ),
              ],
            ),
          );
        }),
      ),
    );
  }

  Widget _buildNavigationButtons(int currentStep) {
    return Container(
      padding: const EdgeInsets.all(16),
      decoration: BoxDecoration(
        color: Theme.of(context).scaffoldBackgroundColor,
        boxShadow: [
          BoxShadow(
            color: Colors.black.withValues(alpha: 0.1),
            blurRadius: 8,
            offset: const Offset(0, -2),
          ),
        ],
      ),
      child: SafeArea(
        child: Row(
          children: [
            if (currentStep > 0)
              Expanded(
                child: OutlinedButton(
                  onPressed: _previousStep,
                  child: const Text('Précédent'),
                ),
              ),
            if (currentStep > 0) const SizedBox(width: 16),
            Expanded(
              child: ElevatedButton(
                onPressed: _nextStep,
                child: Text(currentStep < 5 ? 'Suivant' : 'Publier'),
              ),
            ),
          ],
        ),
      ),
    );
  }

  void _showExitConfirmation(BuildContext context) {
    showDialog(
      context: context,
      builder: (context) => AlertDialog(
        title: const Text('Quitter'),
        content: const Text(
            'Voulez-vous vraiment quitter ? Vos modifications seront perdues.'),
        actions: [
          TextButton(
            onPressed: () => Navigator.pop(context),
            child: const Text('Annuler'),
          ),
          TextButton(
            onPressed: () {
              Navigator.pop(context);
              context.pop();
            },
            style: TextButton.styleFrom(foregroundColor: AppColors.error),
            child: const Text('Quitter'),
          ),
        ],
      ),
    );
  }
}

/// Étape 1: Informations de base
class _Step1BasicInfo extends ConsumerWidget {
  final GlobalKey<FormState> formKey;

  const _Step1BasicInfo({required this.formKey});

  @override
  Widget build(BuildContext context, WidgetRef ref) {
    return Form(
      key: formKey,
      child: ListView(
        padding: const EdgeInsets.all(16),
        children: [
          Text(
            'Informations de base',
            style: Theme.of(context).textTheme.headlineSmall,
          ),
          const SizedBox(height: 8),
          Text(
            'Commencez par les informations essentielles de votre bien',
            style: Theme.of(context).textTheme.bodyMedium?.copyWith(
                  color: AppColors.grey600,
                ),
          ),
          const SizedBox(height: 24),

          // Titre
          TextFormField(
            decoration: const InputDecoration(
              labelText: 'Titre de l\'annonce *',
              hintText: 'Ex: Appartement moderne 2 chambres à Lomé',
              prefixIcon: Icon(Icons.title),
            ),
            maxLength: 100,
            validator: (value) {
              if (value == null || value.isEmpty) {
                return 'Le titre est requis';
              }
              if (value.length < 10) {
                return 'Le titre doit contenir au moins 10 caractères';
              }
              return null;
            },
            onSaved: (value) {
              ref.read(listingFormProvider.notifier).update((state) {
                return {...state, 'title': value};
              });
            },
          ),
          const SizedBox(height: 16),

          // Description
          TextFormField(
            decoration: const InputDecoration(
              labelText: 'Description *',
              hintText: 'Décrivez votre bien en détail...',
              prefixIcon: Icon(Icons.description),
              alignLabelWithHint: true,
            ),
            maxLines: 6,
            maxLength: 1000,
            validator: (value) {
              if (value == null || value.isEmpty) {
                return 'La description est requise';
              }
              if (value.length < 50) {
                return 'La description doit contenir au moins 50 caractères';
              }
              return null;
            },
            onSaved: (value) {
              ref.read(listingFormProvider.notifier).update((state) {
                return {...state, 'description': value};
              });
            },
          ),
          const SizedBox(height: 16),

          // Type de logement
          DropdownButtonFormField<ListingType>(
            decoration: const InputDecoration(
              labelText: 'Type de logement *',
              prefixIcon: Icon(Icons.home),
            ),
            items: ListingType.values.map((type) {
              return DropdownMenuItem(
                value: type,
                child: Text(type.displayName),
              );
            }).toList(),
            validator: (value) {
              if (value == null) {
                return 'Le type de logement est requis';
              }
              return null;
            },
            onChanged: (value) {},
            onSaved: (value) {
              ref.read(listingFormProvider.notifier).update((state) {
                return {...state, 'type': value?.name};
              });
            },
          ),
          const SizedBox(height: 16),

          // Prix
          TextFormField(
            decoration: const InputDecoration(
              labelText: 'Prix mensuel (FCFA) *',
              prefixText: 'FCFA ',
              prefixIcon: Icon(Icons.payments),
            ),
            keyboardType: TextInputType.number,
            validator: (value) {
              if (value == null || value.isEmpty) {
                return 'Le prix est requis';
              }
              final price = double.tryParse(value);
              if (price == null || price <= 0) {
                return 'Veuillez entrer un prix valide';
              }
              return null;
            },
            onSaved: (value) {
              ref.read(listingFormProvider.notifier).update((state) {
                return {...state, 'price': double.parse(value!)};
              });
            },
          ),
        ],
      ),
    );
  }
}

/// Étape 2: Localisation
class _Step2Location extends ConsumerStatefulWidget {
  final GlobalKey<FormState> formKey;

  const _Step2Location({required this.formKey});

  @override
  ConsumerState<_Step2Location> createState() => _Step2LocationState();
}

class _Step2LocationState extends ConsumerState<_Step2Location> {
  String? _selectedCity;

  @override
  Widget build(BuildContext context) {
    return Form(
      key: widget.formKey,
      child: ListView(
        padding: const EdgeInsets.all(16),
        children: [
          Text(
            'Localisation',
            style: Theme.of(context).textTheme.headlineSmall,
          ),
          const SizedBox(height: 8),
          Text(
            'Indiquez où se trouve votre bien',
            style: Theme.of(context).textTheme.bodyMedium?.copyWith(
                  color: AppColors.grey600,
                ),
          ),
          const SizedBox(height: 24),

          // Ville
          DropdownButtonFormField<String>(
            decoration: const InputDecoration(
              labelText: 'Ville *',
              prefixIcon: Icon(Icons.location_city),
            ),
            items: TogoLocations.allCities.map((city) {
              return DropdownMenuItem(value: city, child: Text(city));
            }).toList(),
            validator: (value) {
              if (value == null) {
                return 'La ville est requise';
              }
              return null;
            },
            onChanged: (value) {
              setState(() {
                _selectedCity = value;
              });
            },
            onSaved: (value) {
              ref.read(listingFormProvider.notifier).update((state) {
                return {...state, 'city': value};
              });
            },
          ),
          const SizedBox(height: 16),

          // Quartier
          DropdownButtonFormField<String>(
            decoration: const InputDecoration(
              labelText: 'Quartier *',
              prefixIcon: Icon(Icons.location_on),
            ),
            items: _selectedCity != null
                ? TogoLocations.getNeighborhoods(_selectedCity!).map((n) {
                    return DropdownMenuItem(value: n, child: Text(n));
                  }).toList()
                : [],
            validator: (value) {
              if (value == null) {
                return 'Le quartier est requis';
              }
              return null;
            },
            onChanged: _selectedCity == null ? null : (value) {},
            onSaved: (value) {
              ref.read(listingFormProvider.notifier).update((state) {
                return {...state, 'neighborhood': value};
              });
            },
          ),
          const SizedBox(height: 16),

          // Adresse complète
          TextFormField(
            decoration: const InputDecoration(
              labelText: 'Adresse complète *',
              hintText: 'Ex: Rue 123, près de...',
              prefixIcon: Icon(Icons.home_outlined),
            ),
            maxLines: 2,
            validator: (value) {
              if (value == null || value.isEmpty) {
                return 'L\'adresse est requise';
              }
              return null;
            },
            onSaved: (value) {
              ref.read(listingFormProvider.notifier).update((state) {
                return {...state, 'address': value};
              });
            },
          ),
          const SizedBox(height: 16),

          // Coordonnées GPS (optionnel)
          Card(
            child: Padding(
              padding: const EdgeInsets.all(16),
              child: Column(
                crossAxisAlignment: CrossAxisAlignment.start,
                children: [
                  const Row(
                    children: [
                      Icon(Icons.my_location, color: AppColors.primary),
                      SizedBox(width: 8),
                      Text(
                        'Coordonnées GPS (optionnel)',
                        style: TextStyle(fontWeight: FontWeight.w600),
                      ),
                    ],
                  ),
                  const SizedBox(height: 12),
                  Row(
                    children: [
                      Expanded(
                        child: TextFormField(
                          decoration: const InputDecoration(
                            labelText: 'Latitude',
                            hintText: '6.131944',
                          ),
                          keyboardType: TextInputType.number,
                        ),
                      ),
                      const SizedBox(width: 16),
                      Expanded(
                        child: TextFormField(
                          decoration: const InputDecoration(
                            labelText: 'Longitude',
                            hintText: '1.222778',
                          ),
                          keyboardType: TextInputType.number,
                        ),
                      ),
                    ],
                  ),
                  const SizedBox(height: 8),
                  TextButton.icon(
                    icon: const Icon(Icons.gps_fixed),
                    label: const Text('Utiliser ma position'),
                    onPressed: () async {
                      try {
                        // Note: Requires geolocator package
                        // For now, show a message that this feature needs setup
                        ScaffoldMessenger.of(context).showSnackBar(
                          const SnackBar(
                            content: Text(
                              'Fonctionnalité GPS nécessite le package geolocator. '
                              'Veuillez entrer les coordonnées manuellement.',
                            ),
                          ),
                        );
                        // TODO: Uncomment after adding geolocator package
                        // final position = await Geolocator.getCurrentPosition();
                        // ref.read(listingFormProvider.notifier).update((state) {
                        //   return {
                        //     ...state,
                        //     'latitude': position.latitude,
                        //     'longitude': position.longitude,
                        //   };
                        // });
                      } catch (e) {
                        if (context.mounted) {
                          ScaffoldMessenger.of(context).showSnackBar(
                            SnackBar(content: Text('Erreur GPS: $e')),
                          );
                        }
                      }
                    },
                  ),
                ],
              ),
            ),
          ),
        ],
      ),
    );
  }
}

/// Étape 3: Détails
class _Step3Details extends ConsumerWidget {
  final GlobalKey<FormState> formKey;

  const _Step3Details({required this.formKey});

  @override
  Widget build(BuildContext context, WidgetRef ref) {
    return Form(
      key: formKey,
      child: ListView(
        padding: const EdgeInsets.all(16),
        children: [
          Text(
            'Détails du logement',
            style: Theme.of(context).textTheme.headlineSmall,
          ),
          const SizedBox(height: 8),
          Text(
            'Précisez les caractéristiques de votre bien',
            style: Theme.of(context).textTheme.bodyMedium?.copyWith(
                  color: AppColors.grey600,
                ),
          ),
          const SizedBox(height: 24),

          // Surface
          TextFormField(
            decoration: const InputDecoration(
              labelText: 'Surface (m²) *',
              suffixText: 'm²',
              prefixIcon: Icon(Icons.square_foot),
            ),
            keyboardType: TextInputType.number,
            validator: (value) {
              if (value == null || value.isEmpty) {
                return 'La surface est requise';
              }
              final area = double.tryParse(value);
              if (area == null || area <= 0) {
                return 'Veuillez entrer une surface valide';
              }
              return null;
            },
            onSaved: (value) {
              ref.read(listingFormProvider.notifier).update((state) {
                return {...state, 'area': double.parse(value!)};
              });
            },
          ),
          const SizedBox(height: 16),

          // Nombre de chambres
          DropdownButtonFormField<int>(
            decoration: const InputDecoration(
              labelText: 'Nombre de chambres *',
              prefixIcon: Icon(Icons.bed),
            ),
            items: List.generate(10, (i) => i).map((n) {
              return DropdownMenuItem(
                value: n,
                child:
                    Text(n == 0 ? 'Studio' : '$n chambre${n > 1 ? 's' : ''}'),
              );
            }).toList(),
            validator: (value) {
              if (value == null) {
                return 'Le nombre de chambres est requis';
              }
              return null;
            },
            onChanged: (value) {},
            onSaved: (value) {
              ref.read(listingFormProvider.notifier).update((state) {
                return {...state, 'bedrooms': value};
              });
            },
          ),
          const SizedBox(height: 16),

          // Nombre de salles de bain
          DropdownButtonFormField<int>(
            decoration: const InputDecoration(
              labelText: 'Nombre de salles de bain *',
              prefixIcon: Icon(Icons.bathroom),
            ),
            items: List.generate(6, (i) => i + 1).map((n) {
              return DropdownMenuItem(
                value: n,
                child: Text('$n salle${n > 1 ? 's' : ''} de bain'),
              );
            }).toList(),
            validator: (value) {
              if (value == null) {
                return 'Le nombre de salles de bain est requis';
              }
              return null;
            },
            onChanged: (value) {},
            onSaved: (value) {
              ref.read(listingFormProvider.notifier).update((state) {
                return {...state, 'bathrooms': value};
              });
            },
          ),
        ],
      ),
    );
  }
}

/// Étape 4: Commodités
class _Step4Amenities extends ConsumerStatefulWidget {
  final GlobalKey<FormState> formKey;

  const _Step4Amenities({required this.formKey});

  @override
  ConsumerState<_Step4Amenities> createState() => _Step4AmenitiesState();
}

class _Step4AmenitiesState extends ConsumerState<_Step4Amenities> {
  final Set<String> _selectedAmenities = {};

  @override
  Widget build(BuildContext context) {
    return Form(
      key: widget.formKey,
      child: ListView(
        padding: const EdgeInsets.all(16),
        children: [
          Text(
            'Commodités',
            style: Theme.of(context).textTheme.headlineSmall,
          ),
          const SizedBox(height: 8),
          Text(
            'Sélectionnez les équipements disponibles',
            style: Theme.of(context).textTheme.bodyMedium?.copyWith(
                  color: AppColors.grey600,
                ),
          ),
          const SizedBox(height: 24),

          // Grouper par catégorie
          ...AmenityCategory.values.map((category) {
            final amenities = Amenities.getByCategory(category);
            if (amenities.isEmpty) return const SizedBox.shrink();

            return Column(
              crossAxisAlignment: CrossAxisAlignment.start,
              children: [
                Text(
                  category.displayName,
                  style: Theme.of(context).textTheme.titleMedium,
                ),
                const SizedBox(height: 12),
                Wrap(
                  spacing: 8,
                  runSpacing: 8,
                  children: amenities.map((amenity) {
                    final isSelected = _selectedAmenities.contains(amenity.id);
                    return FilterChip(
                      label: Text(amenity.name),
                      selected: isSelected,
                      onSelected: (selected) {
                        setState(() {
                          if (selected) {
                            _selectedAmenities.add(amenity.id);
                          } else {
                            _selectedAmenities.remove(amenity.id);
                          }
                        });
                        ref.read(listingFormProvider.notifier).update((state) {
                          return {
                            ...state,
                            'amenities': _selectedAmenities.toList()
                          };
                        });
                      },
                    );
                  }).toList(),
                ),
                const SizedBox(height: 24),
              ],
            );
          }),
        ],
      ),
    );
  }
}

/// Étape 5: Images
class _Step5Images extends ConsumerStatefulWidget {
  final GlobalKey<FormState> formKey;

  const _Step5Images({required this.formKey});

  @override
  ConsumerState<_Step5Images> createState() => _Step5ImagesState();
}

class _Step5ImagesState extends ConsumerState<_Step5Images> {
  final List<XFile> _images = [];
  final ImagePicker _picker = ImagePicker();

  Future<void> _pickImages() async {
    final images = await _picker.pickMultiImage();
    if (images.isNotEmpty) {
      setState(() {
        _images.addAll(images);
      });
      // Sauvegarder les chemins des images
      ref.read(listingFormProvider.notifier).update((state) {
        return {...state, 'images': _images.map((e) => e.path).toList()};
      });
    }
  }

  Future<void> _takePicture() async {
    final image = await _picker.pickImage(source: ImageSource.camera);
    if (image != null) {
      setState(() {
        _images.add(image);
      });
      ref.read(listingFormProvider.notifier).update((state) {
        return {...state, 'images': _images.map((e) => e.path).toList()};
      });
    }
  }

  void _removeImage(int index) {
    setState(() {
      _images.removeAt(index);
    });
    ref.read(listingFormProvider.notifier).update((state) {
      return {...state, 'images': _images.map((e) => e.path).toList()};
    });
  }

  @override
  Widget build(BuildContext context) {
    return Form(
      key: widget.formKey,
      child: ListView(
        padding: const EdgeInsets.all(16),
        children: [
          Text(
            'Photos du logement',
            style: Theme.of(context).textTheme.headlineSmall,
          ),
          const SizedBox(height: 8),
          Text(
            'Ajoutez au moins 3 photos de qualité',
            style: Theme.of(context).textTheme.bodyMedium?.copyWith(
                  color: AppColors.grey600,
                ),
          ),
          const SizedBox(height: 24),

          // Boutons d'ajout
          Row(
            children: [
              Expanded(
                child: OutlinedButton.icon(
                  icon: const Icon(Icons.photo_library),
                  label: const Text('Galerie'),
                  onPressed: _pickImages,
                ),
              ),
              const SizedBox(width: 16),
              Expanded(
                child: OutlinedButton.icon(
                  icon: const Icon(Icons.camera_alt),
                  label: const Text('Appareil photo'),
                  onPressed: _takePicture,
                ),
              ),
            ],
          ),
          const SizedBox(height: 24),

          // Grille d'images
          if (_images.isEmpty)
            Card(
              child: Padding(
                padding: const EdgeInsets.all(48),
                child: Column(
                  children: [
                    Icon(
                      Icons.add_photo_alternate,
                      size: 64,
                      color: Colors.grey[400],
                    ),
                    const SizedBox(height: 16),
                    Text(
                      'Aucune photo ajoutée',
                      style: TextStyle(color: Colors.grey[600]),
                    ),
                  ],
                ),
              ),
            )
          else
            GridView.builder(
              shrinkWrap: true,
              physics: const NeverScrollableScrollPhysics(),
              gridDelegate: const SliverGridDelegateWithFixedCrossAxisCount(
                crossAxisCount: 3,
                crossAxisSpacing: 8,
                mainAxisSpacing: 8,
              ),
              itemCount: _images.length,
              itemBuilder: (context, index) {
                return Stack(
                  children: [
                    ClipRRect(
                      borderRadius: BorderRadius.circular(8),
                      child: Image.network(
                        _images[index].path,
                        width: double.infinity,
                        height: double.infinity,
                        fit: BoxFit.cover,
                        errorBuilder: (_, __, ___) => Container(
                          color: AppColors.grey300,
                          child: const Icon(Icons.image),
                        ),
                      ),
                    ),
                    Positioned(
                      top: 4,
                      right: 4,
                      child: CircleAvatar(
                        radius: 16,
                        backgroundColor: AppColors.error,
                        child: IconButton(
                          padding: EdgeInsets.zero,
                          icon: const Icon(Icons.close,
                              size: 16, color: AppColors.white),
                          onPressed: () => _removeImage(index),
                        ),
                      ),
                    ),
                    if (index == 0)
                      Positioned(
                        bottom: 4,
                        left: 4,
                        child: Container(
                          padding: const EdgeInsets.symmetric(
                              horizontal: 8, vertical: 4),
                          decoration: BoxDecoration(
                            color: AppColors.primary,
                            borderRadius: BorderRadius.circular(4),
                          ),
                          child: const Text(
                            'Principale',
                            style:
                                TextStyle(color: AppColors.white, fontSize: 10),
                          ),
                        ),
                      ),
                  ],
                );
              },
            ),

          if (_images.isNotEmpty) ...[
            const SizedBox(height: 16),
            Text(
              '${_images.length} photo${_images.length > 1 ? 's' : ''} ajoutée${_images.length > 1 ? 's' : ''}',
              style: Theme.of(context).textTheme.bodySmall,
              textAlign: TextAlign.center,
            ),
            const SizedBox(height: 8),
            const Text(
              'La première photo sera utilisée comme image principale',
              style: TextStyle(fontSize: 12, color: AppColors.grey600),
              textAlign: TextAlign.center,
            ),
          ],
        ],
      ),
    );
  }
}

/// Étape 6: Révision
class _Step6Review extends ConsumerWidget {
  final GlobalKey<FormState> formKey;

  const _Step6Review({required this.formKey});

  @override
  Widget build(BuildContext context, WidgetRef ref) {
    final formData = ref.watch(listingFormProvider);

    return Form(
      key: formKey,
      child: ListView(
        padding: const EdgeInsets.all(16),
        children: [
          Text(
            'Révision',
            style: Theme.of(context).textTheme.headlineSmall,
          ),
          const SizedBox(height: 8),
          Text(
            'Vérifiez les informations avant de publier',
            style: Theme.of(context).textTheme.bodyMedium?.copyWith(
                  color: AppColors.grey600,
                ),
          ),
          const SizedBox(height: 24),

          // Résumé des informations
          _buildReviewSection('Informations de base', [
            _buildReviewItem('Titre', formData['title'] ?? 'Non renseigné'),
            _buildReviewItem(
                'Description', formData['description'] ?? 'Non renseigné'),
            _buildReviewItem('Type', formData['type'] ?? 'Non renseigné'),
            _buildReviewItem('Prix', '${formData['price'] ?? 0} FCFA/mois'),
          ]),

          const SizedBox(height: 16),

          _buildReviewSection('Localisation', [
            _buildReviewItem('Ville', formData['city'] ?? 'Non renseigné'),
            _buildReviewItem(
                'Quartier', formData['neighborhood'] ?? 'Non renseigné'),
            _buildReviewItem('Adresse', formData['address'] ?? 'Non renseigné'),
          ]),

          const SizedBox(height: 16),

          _buildReviewSection('Détails', [
            _buildReviewItem('Surface', '${formData['area'] ?? 0} m²'),
            _buildReviewItem('Chambres', '${formData['bedrooms'] ?? 0}'),
            _buildReviewItem('Salles de bain', '${formData['bathrooms'] ?? 0}'),
          ]),

          const SizedBox(height: 16),

          _buildReviewSection('Commodités', [
            Text(
              '${(formData['amenities'] as List?)?.length ?? 0} commodité(s) sélectionnée(s)',
              style: Theme.of(context).textTheme.bodyMedium,
            ),
          ]),

          const SizedBox(height: 16),

          _buildReviewSection('Photos', [
            Text(
              '${(formData['images'] as List?)?.length ?? 0} photo(s) ajoutée(s)',
              style: Theme.of(context).textTheme.bodyMedium,
            ),
          ]),
        ],
      ),
    );
  }

  Widget _buildReviewSection(String title, List<Widget> children) {
    return Card(
      child: Padding(
        padding: const EdgeInsets.all(16),
        child: Column(
          crossAxisAlignment: CrossAxisAlignment.start,
          children: [
            Text(
              title,
              style: const TextStyle(
                fontSize: 16,
                fontWeight: FontWeight.bold,
              ),
            ),
            const Divider(),
            ...children,
          ],
        ),
      ),
    );
  }

  Widget _buildReviewItem(String label, String value) {
    return Padding(
      padding: const EdgeInsets.symmetric(vertical: 4),
      child: Row(
        crossAxisAlignment: CrossAxisAlignment.start,
        children: [
          SizedBox(
            width: 120,
            child: Text(
              '$label:',
              style: const TextStyle(
                fontWeight: FontWeight.w600,
                color: AppColors.grey600,
              ),
            ),
          ),
          Expanded(
            child: Text(value),
          ),
        ],
      ),
    );
  }
}
